-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
from BOOK, AUTHOR
where BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID and CATEGORY = '경제'
order by DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d')